name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: './package-lock.json'  # Changed path

      - name: Install dependencies
        working-directory: .  # Changed working directory
        run: npm ci

      - name: Build website
        working-directory: .  # Changed working directory
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build  # Changed build output path
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
